### ISSUE TITLE
codeAction returns command which does seems to be supported by all LSP implementations

### ISSUE THREAD

**Issue by jeffmaury** [fabric8-analytics/fabric8-analytics-lsp-server#95]
code fixes are implemented as code actions and current implementation returns commands instead of code actions. This seems not equaly supported by LSP implementations (at least by intellij-lsp) so could be nice to return code actions instead of commands

**Comment by jeffmaury** [comment]
As this is a substancial change, it's important to validate all environments so I list them so that we can check them
- [ ] VSCode
-  [ ] Eclipse / JBoss Tools
 - [ ] IntelliJ

**Comment by invincibleJai** [comment]
@jeffmaury for VSCode we needed to handle the command in client in order to apply fixes as in https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/blob/master/src/extension.ts#L28-L42. 

With code actions implementation, does client needs to hand it as was the case for command as above

**Comment by jeffmaury** [comment]
No with my PR you don't need to register a command anymore
